markdown: kramdown
title: Star Sanctuary
description:
color: 00FF00
icon:
discord: https://discord.gg/Uz6f8HU

jQuery: https://code.jquery.com/jquery-3.4.1.min.js
BootstrapCSS: https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css
BootstrapJS: https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js
FontAwesome: https://kit.fontawesome.com/2cc38ba94d.js
TwitchJS: https://embed.twitch.tv/embed/v1.js